<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE planets [
<!ELEMENT planets (title, planet+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT planet (name, distance,  diameter, description)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT distance (#PCDATA)>
<!ELEMENT diameter (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ENTITY Mercury "Меркурий">
<!ENTITY Venus "Венера">
<!ENTITY Earth "Земля">
<!ENTITY Mars "Марс">
<!ENTITY Jupiter "Юпитер">
<!ENTITY Saturn "Сатурн">
<!ENTITY Uranus "Уран">
<!ENTITY Neptune "Нептун">
]>
<planets>
<title>Планеты солнечной системы</title>

  <planet>
    <name>&Mercury;</name>
    <distance>57,9 млн км</distance>
    <diameter>4879 км</diameter>
    <description>
    Меркурий очень маленький, у него нет атмосферы, в этом смысле он вообще очень похож на Луну. 
    Подсолнечная сторона Меркурия нагрета до очень высокой температуры, а ночная сторона из-за отсутствия 
    атмосферы охлаждается до очень низких температур. Несмотря на то, что Меркурий близко находится к Земле, 
    эта планета мало изучена, потому что лететь к ней очень трудно. Земля со скоростью 30 км/с вращается вокруг 
    Солнца. Получается, будто вы мчитесь на скоростном поезде, а Меркурий — это маленький полустанок, на котором 
    вы не можете сойти: вы его видите, он близко, но поезд несется. Нужно предпринять какие-то специальные усилия, 
    чтобы на нем выскочить. Например, слететь с поезда с ракетным ранцем и отрулить на этот полустанок — использовать очень мощные средства.
    </description>
  </planet>
  <planet>
    <name>&Venus;</name>
    <distance>108,2 млн км</distance>
    <diameter>12104 км</diameter>
    <description>Следующая планета от Солнца — Венера. Мы знаем, что у нее есть атмосфера. Впервые ее обнаружил еще Михаил 
    Ломоносов во время очень редкого события — прохождения Венеры по диску Солнца. Так что люди уже довольно давно могли фантазировать 
    о том, что на Венере может быть жизнь. Но на Венере слишком жарко, и атмосфера состоит вовсе не из того, чего хотелось бы земным живым
     существам. Так что, по всей видимости, жизни на Венере нет. Но чуть больше года назад одна из групп наблюдателей обнаружила в атмосфере 
     Венеры фосфин. Молекула фосфина включает в себя фосфор, а он, в свою очередь, участвует в биологических процессах. Точный ответ дадут 
     только прямые измерения в атмосфере Венеры. Это очень интересно, потому что в течение долгого времени Венера была вычеркнута из списка 
     потенциально обитаемых объектов Солнечной системы.
</description>
  </planet>
  <planet>
    <name>&Earth;</name>
    <distance>149,6 млн км</distance>
    <diameter>12756 км</diameter>
    <description>Единственная планета, на которой известна жизнь, имеющая умеренный климат и большое разнообразие ландшафтов и биосферы. В океанах и морях Земли содержится 1370 млн. км3 воды.
     Чтобы представить себе, как велико это количество, достаточно сказать, что оно в 10 раз больше объема суши, возвышающейся над уровнем моря.
      Высокогорные ледники и полярные льды Арктики и Антарктики связали более 30 млн. км3 воды. Если бы этот лед растопить, уровень океана поднялся
       и вода затопила бы около одной восьмой части суши, многие приморские города оказались бы под водой. В озерах и реках находится 4 млн., 
       а в атмосфере в виде водяных паров до 12 тыс. км3 воды. В толще земной коры заключено около 100 млн. км3 воды.</description>
  </planet>
  <planet>
    <name>&Mars;</name>
    <distance>227,9 млн км</distance>
    <diameter>6792 км</diameter>
    <description>В свое время Марс был кандидатом номер один в обитаемые объекты Солнечной системы. Он гораздо меньше Земли: по массе Марс в десять раз уступает нашей планете.
     У него есть атмосфера, но она очень разреженная. Именно поэтому на поверхность Марса так трудно спускать аппараты.
Несмотря на то, что сейчас мы получаем отрицательные результаты насчет обитаемости Марса, сохраняется очень интересная 
возможность: Марс мог быть обитаемым в прошлом. Есть очень надежные данные о том, что климат Марса миллиарды лет назад 
был совсем другим. Это была короткая эпоха, что может являться хорошим аргументом против существования жизни, ведь для ее 
появления нужно долгое время. Но, тем не менее, эта короткая эпоха все-таки исчислялась сотнями миллионов лет. И в эту эпоху могла 
зародиться жизнь. Потом Марс потерял значительную часть своей атмосферы, климат сильно изменился. У планеты нет сильного магнитного 
поля, которое защищало бы ее от солнечного ветра. Так поток частиц от Солнца потихоньку снес атмосферу.
Но, если жизнь успела появиться и, например, ушла на большую глубину, тогда она могла сохраниться до настоящего времени. 
Но мы пока не умеем проводить глубокое бурение на Марсе. Это просто очень дорого. Кроме того, можно сосредоточиться на более 
простых задачах. Например, на поиске подземных озер в пещерах Марса. Но для этого нужно создать новое поколение марсоходов, 
которые смогут залезать туда, искать, проводить исследования и вылезать наружу.
</description>
  </planet>
  <planet>
    <name>&Jupiter;</name>
    <distance>778,6 млн км</distance>
    <diameter>142984 км</diameter>
    <description>Иногда про Юпитер говорят, что это своего рода недозвезда. На самом деле Юпитеру очень далеко до звезды 
    — ему нужно стать примерно в 80 раз более массивным. Но на звезду он немного похож своим составом из водорода и гелия. 
    Юпитер массивней, чем все остальные планеты, астероиды, пыль, мусор, кометы в Солнечной системе вместе взятые. Так что 
    если бы мы были инопланетными астрономами, которые издалека наблюдают за Солнечной системой, то в течение долгого времени
     мы могли бы регистрировать только пустой Юпитер.
</description>

  </planet>
  <planet>
    <name>&Saturn;</name>
    <distance>1433,5 млн км</distance>
    <diameter>120536 км</diameter>
    <description>Сатурн по размерам меньше, чем Юпитер, но интересен своими замечательными кольцами. Их, кстати, попробовал 
    открыть еще Галилео Галилей, но у него не получилось. В первые телескопы он увидел Сатурн в виде Чебурашки: кружок и какие-то
     странные ушки вокруг. Это его настолько поразило, что, будучи, человеком очень осторожным и консервативным, он не опубликовал 
     свое открытие, но сделал некое зашифрованное сообщение. Когда у Галилея появились более совершенные телескопы, он посмотрел на 
     Сатурн еще раз. И ничего не увидел. Но не потому что это был какой-то дефект, а потому что кольца повернулись ребром. И Галилей
      не стал расшифровывать свое раннее сообщение. А кольца были открыты позже уже Гюйгенсом спустя несколько десятилетий.
</description>
  </planet>
  <planet>
    <name>&Uranus;</name>
    <distance>2872,5 млн км</distance>
    <diameter>51118 км</diameter>
    <description>Планета-гигант, состоящая из льда и газов, имеющая сильно наклоненную ось вращения и тонкие кольца, окружённая 27 спутниками. Земля не единственная голубая планета солнечной системы, таким же цветом может похвастаться и Уран. 
    Эту планету открыл Уильям Гершель в 1781 году, до этого момента, увидев Уран на небе, его принимали за обычную звезду.
     Имя для этого космического тела подобрали в честь древнегреческого божества небес.</description>
  </planet>
  <planet>
    <name>&Neptune;</name>
    <distance>4495,1 млн км</distance>
    <diameter>49528 км</diameter>
    <description>Самая дальняя от Солнца планета, имеющая синий цвет из-за метана в атмосфере, сильные ветры и 14 спутников, включая самый большой — Тритон.Одним из показательных научных достижений, одним из доказательств безграничной познаваемости
     природы стало открытие этой планеты с помощью вычислений. Сатурн много времени считали последней планетой солнечной системы. 
Затем в конце 18 века был открыт Уран, которые с большим трудом можно было заметить невооруженным глазом. К концу 40-х годов 19-го
века наблюдения смогли показать, что Уран немножко уходит с пути, по которым он должен идти с учетом воздействия всех прочих известных планет.
 В связи с этим теория движения космических тел была подвергнута испытанию.</description>
  </planet>
</planets>
